# Generated by Django 2.2.7 on 2020-02-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=8)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=30)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Model')),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
