# Generated by Django 2.2.7 on 2020-02-12 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20200211_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='km_car',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repair',
            name='cost',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repair',
            name='date_reg',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repair',
            name='km_repair',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
